# Generated by Django 5.0.4 on 2024-04-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdminProfile",
        ),
    ]
