# Generated by Django 5.0.4 on 2024-04-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_delete_adminprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientprofile",
            name="is_admin",
        ),
    ]
