# Generated by Django 5.0.4 on 2024-04-10 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dishes", "0005_alter_dishinfo_dish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishinfo",
            name="dish",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="dishes.dish"
            ),
        ),
    ]
