# Generated by Django 5.0.4 on 2024-04-11 05:12

import dishes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dishes",
            "0009_dish_category_dishimages_dish_dishimages_dish_images",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishimages",
            name="dish_images",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=dishes.models.dish_images_file_path,
            ),
        ),
    ]
