# Generated by Django 5.0.4 on 2024-04-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dishes", "0011_category_remove_dish_category_dish_category_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="DishCategory",
        ),
    ]
