# Generated by Django 5.0.4 on 2024-04-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dishes", "0013_rename_category_id_dish_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="dishcategory",
            name="dish_count",
            field=models.IntegerField(default=0),
        ),
    ]
