# Generated by Django 5.0.4 on 2024-04-15 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dishes", "0014_dishcategory_dish_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dishes",
                to="dishes.dishcategory",
            ),
        ),
    ]
