# Generated by Django 5.0.4 on 2024-04-15 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dishes", "0015_alter_dish_category"),
        ("favorites", "0002_rename_user_favorites_profile"),
        ("profiles", "0003_remove_clientprofile_is_admin"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favorites",
            unique_together={("profile", "dish")},
        ),
    ]
