# Generated by Django 5.0.4 on 2024-04-13 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_rename_user_cart_profile"),
        ("dishes", "0014_dishcategory_dish_count"),
        ("profiles", "0003_remove_clientprofile_is_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="count",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="dish",
        ),
        migrations.AlterField(
            model_name="cart",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.clientprofile"
            ),
        ),
        migrations.CreateModel(
            name="CartDish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_dishes",
                        to="cart.cart",
                    ),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dishes.dish"
                    ),
                ),
            ],
            options={
                "unique_together": {("cart", "dish")},
            },
        ),
    ]
