# Generated by Django 5.0.4 on 2024-04-15 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_remove_cart_count_remove_cart_dish_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartdish",
            unique_together=set(),
        ),
    ]
