# Generated by Django 5.0.4 on 2024-04-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_alter_cartdish_unique_together"),
        ("dishes", "0015_alter_dish_category"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartdish",
            unique_together={("cart", "dish")},
        ),
    ]
